### ISSUE TITLE
load controlnet twice when using together

### ISSUE THREAD

**Issue by AlbieRWang** [ototadana/sd-face-editor#10]
sir this extension is very useful for distant view, i try to use it with controlnet ,and controlnet load twice, is it normal or it can be optimized:
![image](https://user-images.githubusercontent.com/28641863/231426959-dccc2f02-99fb-4a97-b904-ae3cdd81c157.png)

**Comment by ototadana** [comment]
@AlbieRWang 
Thanks for the feedback.
I had not envisioned using it in combination with ControlNet. I see, so it can be used that way. Thanks for letting me know.
Fixed to not load twice when used with ControlNet. Please try it!
