### ISSUE TITLE
Stopped working once Lora weight block is enabled 

### ISSUE THREAD

**Issue by Gh20221205** [ototadana/sd-face-editor#104]
I updated A1111 to 1.4, everything seems working except for face editor. It says face detected and my lora processed in the command window, no error message, but the face was not changed. I tried reinstall face editor, same. I'm not sure if it's me alone. 

Update: I think I had the cause pinned down. It's the extension called Lora block weight https://github.com/hako-mikan/sd-webui-lora-block-weight. Once I have it disabled, face editor works as it is supposed to. This conflict only happens after I updated A1111 to 1.4.

**Comment by ototadana** [comment]
Thanks for the report.

I have also updated to 1.4 to check the operation and it seems to be working as before without any problems.

The detected faces not changing may be another problem. Could you try setting "Show intermediate steps" to enabled? If the entire mask image is displayed as black, the face will not be changed. We are working on improving this issue, so please wait a little longer.

**Comment by Gh20221205** [comment]
After enabling Show intermediate steps, it seems my face editor will generate a face, but this face is from checkpoint instead of my lora.

**Comment by Gh20221205** [comment]
> Thanks for the report.
> 
> I have also updated to 1.4 to check the operation and it seems to be working as before without any problems.
> 
> The detected faces not changing may be another problem. Could you try setting "Show intermediate steps" to enabled? If the entire mask image is displayed as black, the face will not be changed. We are working on improving this issue, so please wait a little longer.

I think I have the cause pinned down. It's the extension called Lora block weight https://github.com/hako-mikan/sd-webui-lora-block-weight. Once I have it disabled, face editor works as it is supposed to. This conflict only happens after I updated A1111 to 1.4.

**Comment by ototadana** [comment]
I tried to get it to work with sd-webui-lora-block-weight, but it didn't work in 1.3 either. If I can reproduce the situation where it works correctly, it might solve the problem... Please let me know if you know of any conditions that would make these work in combination.

**Comment by ototadana** [comment]
@Gh20221205 
Not sure what the reason is, but using the latest version of sd-webui-lora-block-weight seems to work correctly.
