### ISSUE TITLE
Small face is blurry

### ISSUE THREAD

**Issue by vpckso** [ototadana/sd-face-editor#105]
Can replace "Step 2. Crop and Resize the Faces" with upscaler?

**Comment by ototadana** [comment]
I don't think it would be that easy to replace it with upscaler, but it could be remedied in other ways. I would like to see the actual image if possible, is that possible?

**Comment by ototadana** [comment]
@vpckso 
I just happened to get an image with a blurred face, so I immediately checked the effect of applying upscaler. As you said, it did improve the blurriness. However, I found that there is a disadvantage in that it increases the time required to generate the image. Therefore, I am planning to offer this feature as a configuration option.

Now, I found another way to work around this problem. It is to type "blur" in the negative prompt. Please try this as well.

**Comment by ototadana** [comment]
@vpckso 

"Advanced Options - (2) Crop and Resize the Faces" now has an upscaler selector.

Please try it out.

**Comment by vpckso** [comment]
Thank you very much!

I tried upscaler and negative prompt "blur", both results much sharper than default.
