### ISSUE TITLE
Sometimes it is difficult to fix a tilted face.

### ISSUE THREAD

**Issue by fgas453243** [ototadana/sd-face-editor#113]
The face-editor fix in i2i works well most of the time, but can produce distorted faces if the face in the source image is tilted.
I think this is a property of stable diffusion that doesn't produce tilted faces well.
When correcting a tilted face, is it possible to rotate the face upright, generate it, rotate it to the original angle, and merge it?

**Comment by ototadana** [comment]
WOW, that's great!

**Comment by fgas453243** [comment]
Thank you for your prompt response.
#127  is working fine.

Here is a fixed image with the "Adjust tilt for detected faces" option enabled.
![20_result-adjust](https://github.com/ototadana/sd-face-editor/assets/129657025/a502548b-0663-4571-bff8-51bab7715806)
It seems that the tilted face is fixed correctly.

Thank you.

**Comment by ototadana** [comment]
@fgas453243 
Thank you for testing it so quickly.

Actually, I was wondering if I should make some more adjustments regarding the settings, but I have decided to release it in this form first.

Thank you very much!
