### ISSUE TITLE
somthing wrong "KeyError: 'face_processor `img2img` does not exist'"

### ISSUE THREAD

**Issue by jj-a-li** [ototadana/sd-face-editor#119]
............ line 27, in get
        raise KeyError(f"face_processor `{job.face_processor.name}` does not exist")
    KeyError: 'face_processor `img2img` does not exist'

**Comment by jj-a-li** [comment]
"unsupported operand type(s) for |: 'type' and 'type'"
when webui start

**Comment by jj-a-li** [comment]
it seems work on webui v1.3.2，but not working on webui v.1.4.0

**Comment by ototadana** [comment]
@jj-a-li 
Thanks for the error report.

Can you give us some more information about the error when starting the Web UI? Please post a Traceback like #21 so we can identify where the problem can occur.

I am also using 1.4.0 and do not have this problem, so I am assuming that there is another factor involved.

**Comment by jj-a-li** [comment]
/mnt/workspace/stable-diffusion-webui/extensions/sd-face-editor/scripts/inferencers/img2img_face_processor.py : unsupported operand type(s) for |: 'type' and 'type'
/mnt/workspace/stable-diffusion-webui/extensions/sd-face-editor/scripts/inferencers/img2img_face_processor.py : unsupported operand type(s) for |: 'type' and 'type'
/mnt/workspace/stable-diffusion-webui/extensions/sd-face-editor/scripts/inferencers/img2img_face_processor.py : unsupported operand type(s) for |: 'type' and 'type'

this error display when webui start，it happening  only in 1.4.0(I have two server)

*** Error running postprocess: /mnt/workspace/stable-diffusion-webui/extensions/sd-face-editor/scripts/face_editor_extension.py
    Traceback (most recent call last):
      File "/mnt/workspace/stable-diffusion-webui/modules/scripts.py", line 498, in postprocess
        script.postprocess(p, processed, *script_args)
      File "/mnt/workspace/stable-diffusion-webui/extensions/sd-face-editor/scripts/face_editor_extension.py", line 53, in postprocess
        ImageProcessor(WorkflowManager.get(option.workflow)).proc_images(o, res, option)
      File "/mnt/workspace/stable-diffusion-webui/extensions/sd-face-editor/scripts/use_cases/workflow_manager.py", line 27, in get
        raise KeyError(f"face_processor `{job.face_processor.name}` does not exist")
    KeyError: 'face_processor `img2img` does not exist'

and this error would display when i try to generating picture

**Comment by ototadana** [comment]
@jj-a-li 
Thanks for the information.
Perhaps this is because the version of Python in the environment where 1.4.0 is running is older than 3.10.

I have changed the code to work with older versions of Python, so please give it a try.

**Comment by jj-a-li** [comment]
already testing for several time ，error fixed ，thanks
