### ISSUE TITLE
one 奇葩的 error,face was generated in temp,but no composite picture result.

### ISSUE THREAD

**Issue by dundund** [ototadana/sd-face-editor#130]
本来正常使用几个月了,今天下午搭配controlnet 之类的扩展,用着用着就报错了,生成了
This afternoon, I used face editor to img2img, combined with controlnet,addtional network and 3d openpose. After a series of operations, Face-Editor cannot work. The error is as follows:
*** Error running postprocess: D:\novelai-webui-aki-v3A\extensions\sd-face-editor\scripts\face_editor_extension.py
    Traceback (most recent call last):
      File "D:\novelai-webui-aki-v3A\modules\scripts.py", line 498, in postprocess
        script.postprocess(p, processed, *script_args)
      File "D:\novelai-webui-aki-v3A\extensions\sd-face-editor\scripts\face_editor_extension.py", line 53, 
in postprocess
        ImageProcessor(WorkflowManager.get(option.workflow)).proc_images(o, res, option)
      File "D:\novelai-webui-aki-v3A\extensions\sd-face-editor\scripts\use_cases\image_processor.py", line 61, 
in proc_images
        proc = self.proc_image(p, option, image)
      File "D:\novelai-webui-aki-v3A\extensions\sd-face-editor\scripts\use_cases\image_processor.py", line 160, 
in proc_image
        mask_image = self.workflow.generate_mask(jobs, face_image, face, option)
      File "D:\novelai-webui-aki-v3A\extensions\sd-face-editor\scripts\use_cases\workflow_manager.py", line 165, 
in generate_mask
        m = mask_generator.generate_mask(image, face_area_on_image, **params)
      File "D:\novelai-webui-aki-v3A\extensions\sd-face-editor\scripts\inferencers\bisenet_mask_generator.py", line 62, 
in generate_mask
        mask = self.fallback_mask_generator.generate_mask(face_image, face_area_on_image, use_minimal_area=True)
      File "D:\novelai-webui-aki-v3A\extensions\sd-face-editor\scripts\inferencers\vignette_mask_generator.py", 
line 42, in generate_mask
        mask[top : top + h, left : left + w] = gaussian_mask
ValueError: could not broadcast input array from shape (479,348) into shape (369,304)
img2img, which draws the face but has no output and does not show the intermediate steps

This problem occurred, but I couldn't solve it. Interestingly, in the process of disabling plug-ins,face editor worked properly once, only once, and then I disabled plug-ins again, until all of them were disabled,face editor still didn't work.
I didn't update anything, but my startup manager will automatically update some components in the extensions-builtin folder such as lora,ldsr, and they are even disabled by me.
I tried to update the version of webui to 1.4, but there was no result. The face editor version 6-19 could not be used, so I updated to the latest version, but it still could not be used.
I can only use the earliest simple script version for now.
I don't want to try to redeploy the webui, the above error persists after I remove scripts and extensions,extensions-builtin(leaving only ScuNET).

When I restore all the extensions, it gets a new error.
*********************************************************
Error loading script: face_editor.py
Traceback (most recent call last):
  File "D:\novelai-webui-aki-v3A\modules\scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\novelai-webui-aki-v3A\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "&lt;
frozen importlib._bootstrap_external&gt;"
, line 883, in exec_module
  File "&lt;
frozen importlib._bootstrap&gt;"
, line 241, in _call_with_frames_removed
  File "D:\novelai-webui-aki-v3A\extensions\sd-face-editor\scripts\face_editor.py", line 6, in &lt;
module&gt;
    from scripts.inferencers.factory import InferencerFactory
ModuleNotFoundError: No module named 'scripts.inferencers.factory'
Tip: The Python runtime threw an exception.
Please check the troubleshooting page.

Error loading script: face_editor_extension.py
Traceback (most recent call last):
  File "D:\novelai-webui-aki-v3A\modules\scripts.py", line 257, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\novelai-webui-aki-v3A\modules\script_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "&lt;
frozen importlib._bootstrap_external&gt;"
, line 883, in exec_module
  File "&lt;
frozen importlib._bootstrap&gt;"
, line 241, in _call_with_frames_removed
  File "D:\novelai-webui-aki-v3A\extensions\sd-face-editor\scripts\face_editor_extension.py", line 4, in &lt;
module&gt;
    from scripts.inferencers.factory import InferencerFactory
ModuleNotFoundError: No module named 'scripts.inferencers.factory'
************************************************************************
I turned the computer back on an hour later, then searched the _pycache_ folder by Everything SOFT and deleted them all, and the face editor worked correctly.
My error seems to have nothing to do with the extension and webui,face-editor versions, but it appeared without warning.
I've been using txt2img before,
img2img is only in heavy use today

**Comment by dundund** [comment]
This error occurs again when I use the face editor without another plugin,
It worked fine at first, but then I couldn't find a face of the same size, and when I turned on the "Use the smallest area (for near faces) ", it started to work,
Then I could not find it, I reduced the recognition rate of the face, although I could draw the face, but there was no composite picture, and the intermediate step was not displayed.
Then I turned off "Use Minimum Area (for near faces)" and it came back up normally.
Therefore, error has been determined to be the problem of facial recognition, and the previous recognition methods have almost no problems except that they can't identify cartoon characters.
My img2img configuration is 0 redraw, only change the face.

**Comment by dundund** [comment]
By the way, the face size is about 1/16th the size of the entire image, and the face shape is about 12 years old, which seems to be a tipping point since they are all images of similar structures generated by controlnet,
face edit sometimes recognizes and sometimes doesn't,

**Comment by ototadana** [comment]
Thanks for the error report.

I can't imagine the conditions under which it occurs, but the error you first presented can be avoided by taking the following actions, so please try them.

1. use the latest version of Face Editor
2. use the following settings in the Workflow Editor

```
{
    "face_detector": "RetinaFace",
    "rules": {
        "then": {
            "face_processor": "img2img",
            "mask_generator": {
                "name": "BiSeNet",
                "params": {
                    "fallback_ratio": 0
                }
            }
        }
    }
}
```
The difference from the default workflow is that "fallback_ratio" is set to 0.

If this works, you can enter the name of any file in "Save as" and save it, and it will always be available to be recalled as a new workflow.

**Comment by dundund** [comment]
yes,useful,thanks.

**Comment by dundund** [comment]
> Thanks for the error report.
> 
> I can't imagine the conditions under which it occurs, but the error you first presented can be avoided by taking the following actions, so please try them.
> 
> 1. use the latest version of Face Editor
> 2. use the following settings in the Workflow Editor
> 
> ```
> {
>     "face_detector": "RetinaFace",
>     "rules": {
>         "then": {
>             "face_processor": "img2img",
>             "mask_generator": {
>                 "name": "BiSeNet",
>                 "params": {
>                     "fallback_ratio": 0
>                 }
>             }
>         }
>     }
> }
> ```
> 
> The difference from the default workflow is that "fallback_ratio" is set to 0.
> 
> If this works, you can enter the name of any file in "Save as" and save it, and it will always be available to be recalled as a new workflow.

yes,useful,thanks.
