### ISSUE TITLE
The plugin seems unable to read Lora

### ISSUE THREAD

**Issue by ftsgyyds** [ototadana/sd-face-editor#132]
which prevents my facial Lora from continuing to work. 😭😭😭

**Comment by ototadana** [comment]
It appears to be working properly in my environment as shown below, so there may be some difference in the environment.
For example, it will not work if sd-webui-lora-block-weight is used. Please see here: https://github.com/ototadana/sd-face-editor/issues/104#issuecomment-1611920154

with lora (3DMM_V10):
![00255-1226346584](https://github.com/ototadana/sd-face-editor/assets/4137885/045083f6-e51c-463a-860b-7c5829500883)

without lora:
![00259-1226346584](https://github.com/ototadana/sd-face-editor/assets/4137885/0925beef-753b-4762-b652-12585e1fed87)
