### ISSUE TITLE
An error occurred when starting the webui.

### ISSUE THREAD

**Issue by liuwenwu520** [ototadana/sd-face-editor#134]
An error occurred when starting the webui. Does this affect the program from working? How can this problem be resolved?
![Snipaste_2023-07-18_11-45-15](https://github.com/ototadana/sd-face-editor/assets/14996050/11402509-07cc-4c90-9865-032799ad9194)

**Comment by ototadana** [comment]
@liuwenwu520 
Please refer to the following issues: #129, #112

**Comment by liuwenwu520** [comment]
> @liuwenwu520 Please refer to the following issues: #129, #112

Thanks. The problem has been solved, the plugin is working now. It turned out my model had not finished downloading completely.
