### ISSUE TITLE
TypeError: FaceEditorExtension.postprocess() missing 1 required positional argument: 'enabled'

### ISSUE THREAD

**Issue by 0Blueaura** [ototadana/sd-face-editor#137]
I've obviously checked the enable button. I have not installed a Block weight extension, doesn't work with every other extensions disabled, when i choose a script named face editor it works only then. but the tab of the face editor doesn't work by itself. updated to the latest version

**Comment by ototadana** [comment]
Unfortunately, I cannot reproduce this error in my environment.
I looked up the error message and found the following Issue:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/11448

Perhaps it may help you to solve your problem.
