### ISSUE TITLE
Select first female face or only female faces?

### ISSUE THREAD

**Issue by cochese9000** [ototadana/sd-face-editor#139]
Feature Query/Request:  Hi, Is it possible to only select female faces?  I  can see the '||' option for assigning faces when you know the order, but if I am doing batches, then it would be good to always replace the female faces with my character, but to avoid accidentally replacing the male ones with the same prompt.

**Comment by ototadana** [comment]
Thanks for the request.

Using [InsightFace](https://github.com/ototadana/sd-face-editor/tree/main/scripts/inferencers/insightface) Detector, it is possible to determine gender (but it is not 100% correct). So, I would like to implement a mechanism to allow only faces with this attribute to be specified as targets.

**Comment by cochese9000** [comment]
Awesome! I'm familiar with that project via Roop, but no idea how to help right now.  Do you have an architectural/PR standard/spec if I want to create suggest some code?

**Comment by ototadana** [comment]
Implemented.

It is available by following these steps: 
1. Update to the latest version
2. Enable 'insightface' option under "Additional components" in the Face Editor section of the "Settings" tab.
3. Restart Web UI.
4. Enter any prompt for "Prompt for face."
5. Write the following in the workflow editor
    - Specify "InsightFace" as "face_detector".
    - Specify "face?gender=F" in "when/tag".
    - Specify "left" in "when/criteria".
    
 Example Workflow:
 
 ```json
 {
  "face_detector": "InsightFace",
  "rules": {
    "when": {
      "tag": "face?gender=F",
      "criteria": "left"
    },
    "then": {
      "face_processor": "img2img",
      "mask_generator": {
        "name": "BiSeNet",
        "params": {
          "fallback_ratio": 0.1
        }
      }
    }
  }
}
 ```
 
 - **Prompt for face:** `(angry:1.3)`
 
![00020-1226346587](https://github.com/ototadana/sd-face-editor/assets/4137885/b05a2fa1-dfef-4166-af3e-22d385a2cc8b)

- References:
    - [Workflow Editor](https://github.com/ototadana/sd-face-editor/blob/v1.6.1/README.md#workflow-editor)
    - [Insightface Face Detector](https://github.com/ototadana/sd-face-editor/tree/v1.6.1/scripts/inferencers/insightface#1-face-detector)
    - [Example workflow](https://github.com/ototadana/sd-face-editor/blob/v1.6.1/workflows/examples/README.md#example-8-blurring-young-peoples-faces)

** I tried it and found that the accuracy of InsightFace's gender determination was not that good, so I am not sure about its practicality...

**Comment by cochese9000** [comment]
Wow! Amazing! Great work :)  I'll give it a try.  Yes, I hacked my local version of  your extension, just removing the Rects that were marked as Male and I could see from the debug info that it was only about 50% accurate with Gender id.  It might help to give men bears or something.  I'll have a play and let you know if I figure anything out.  Thanks very much! :)

**Comment by cochese9000** [comment]
@ototadana Yep, adding 'with beard' to the male prompts helps a lot with gender ID, or so it seems.  But it doesn't help with the female mis-gendering (as male).  i.e. it can mean it skips the female faces.  It's a lot more useful than it was, though, so thanks.  I'll update again if I find out any more tips.

**Comment by ototadana** [comment]
@cochese9000 Thanks a lot!!
