### ISSUE TITLE
Measured, the effect is very good, but there is one small flaw

### ISSUE THREAD

**Issue by ye-pei-sheng** [ototadana/sd-face-editor#14]
![ComfyUI_03138_](https://user-images.githubusercontent.com/128130872/231822186-c58a1d53-16dc-4cd8-819a-b0b5c5378bfc.png)

There is a clear square border around the head

**Comment by amytong85** [comment]
decrease face margin to 1

**Comment by ototadana** [comment]
@ye-pei-sheng 
Thanks for using this.
To remove the square border, increase the value of "Denoising strength for the **entire** image".
In the case of this image, setting this value to 0.3 or 0.35 will make the border much less noticeable.

**Comment by ye-pei-sheng** [comment]
Great, it turned out that my settings were not precise enough.

Thank you all for your guidance.

Wishing you all a prosperous career。

![ComfyUI_031381_](https://user-images.githubusercontent.com/128130872/231926118-92a69176-6e33-49e0-a2c7-ec7fe5c54a9f.png)
