### ISSUE TITLE
image is hazy after generate

### ISSUE THREAD

**Issue by TITC** [ototadana/sd-face-editor#142]
I followed the guidance [Fixing images that already exist](https://github.com/ototadana/sd-face-editor#fixing-images-that-already-exist), everything is set to default, and then I click "generate", but the image has a grayish and hazy feeling. Why is that?

![image](https://github.com/ototadana/sd-face-editor/assets/35098797/8ef3cfa3-6cbc-4f6f-b5ad-9ceba5693189)
![image](https://github.com/ototadana/sd-face-editor/assets/35098797/ef2aec65-7b87-4236-8f0b-c15a6f7b2faa)

**Comment by ototadana** [comment]
@TITC 

When using the Face Editor with img2img, the entire image will be rewritten in the following cases:

- Denoising strength for the "img2img" is greater than 0.
- When the value of "Denoising strength for the entire image" (Advanced Options - (5) Blend the entire image) in Face Editor is greater than 0.

The screen capture shows that the Denoising strength of img2img is set to 0, so it is possible that the value of "Denoising strength for the entire image" in the Face Editor is set to a value greater than 0.

Could you please check that setting?

Also, in img2img, the prompt needs to be specified. If you transfer the image from the PNG Info tab to img2img, it will paste the prompt used when it was generated by txt2img. You can use that as is, or if you do not rewrite the entire image, you can specify a prompt specifically for redrawing the face.

I think it is very likely that the reason the generated image is hazy is that you have not specified any prompts.

Thanks.

**Comment by TITC** [comment]
Thanks for your response.

The Denoising strength for the entire image is greater than 0 and I have not specified any prompts, that's true. The image is regenerated from an avatar with ControlNet canny type, it hasn't any prompts even I transfer the image from the PNG Info tab to img2img.

![Weixin Image_20230721212527](https://github.com/ototadana/sd-face-editor/assets/35098797/4299e001-caf1-4f55-a047-cac265af9e2b)
---

Now I simply copy and paste the prompt from [image](https://civitai.com/images/1713726?period=Week&periodMode=published&sort=Most+Reactions&view=feed), and modify `Denoising strength for the entire image`=0,but seems still hazy at all image and there is a square area cover the face.

![image](https://github.com/ototadana/sd-face-editor/assets/35098797/449ea7d5-9836-4357-8347-8ebc32b1aaaa)

```
high quality, face portrait photo of 26 y.o european woman, wearing black dress, serious face, detailed face, skin pores, cinematic shot, dramatic lighting

Negative prompt: (deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime), text, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck, BadDream, UnrealisticDream

Steps: 97, Sampler: DPM++ 2S a Karras, CFG scale: 7, Seed: 798713878, Size: 512x520, Model hash: a757fe8b3d, Model: chilloutmix_, Denoising strength: 0, Clip skip: 2, Version: v1.5.1

```

![image](https://github.com/ototadana/sd-face-editor/assets/35098797/0e218854-8eaf-4b2e-a0e6-63dd1939c1d9)

**Comment by ototadana** [comment]
I am not imagining why the entire image is rewritten with this setting :thinking: , so can you give me the following 4 pieces of information?

**1. Information about the image on the right side (the image after Face Editor has processed it) when "Show original image" is enabled.**

There should be more information there than in the image on the left (the image generated by img2img).

For example:

```
high quality, face portrait photo of 26 y.o european woman, wearing black dress, serious face, detailed face, skin pores, cinematic shot, dramatic lighting

Steps: 20, Sampler: DPM++ 2S a Karras, CFG scale: 7, Seed: 798713878, Size: 512x512, Denoising strength: 0, face_editor_enabled: True, face_editor_face_margin: 1.6, face_editor_confidence: 0.97, face_editor_strength1: 0.4, face_editor_strength2: 0, face_editor_max_face_count: 20, face_editor_mask_size: 0, face_editor_mask_blur: 12, face_editor_prompt_for_face: "", face_editor_apply_inside_mask_only: True, face_editor_apply_scripts_to_faces: False, face_editor_face_size: 512, face_editor_use_minimal_area: False, face_editor_ignore_larger_faces: True, face_editor_affected_areas: Face;Hair, face_editor_workflow: "{\n \"face_detector\": \"RetinaFace\",\n \"rules\": {\n \"then\": {\n \"face_processor\": \"img2img\",\n \"mask_generator\": {\n \"name\": \"BiSeNet\",\n \"params\": {\n \"fallback_ratio\": 0.1\n }\n }\n }\n }\n}", face_editor_upscaler: None, face_editor_tilt_adjustment_threshold: 40, Version: v1.5.1
```

**2. The left image with "Show original image" enabled.** 

This is the image generated by img2img. I would like to compare the difference between the image on the right side and the image on the left side.

**3. Information displayed in the console at runtime.**

For example:

```
number of faces: 1.                                                | 0/1 [00:00<?, ?it/s]
prompt for the face: high quality, face portrait photo of 26 y.o european woman, wearing black dress, serious face, detailed face, skin pores, cinematic shot, dramatic lighting

100%|██████████████████████████████████████████████████████| 9/9 [00:01<00:00,  5.93it/s]
Total progress: 10it [00:02,  4.58it/s]                                                  
Total progress: 10it [00:02,  5.51it/s]
```

**4. The image generated when the Face Editor is disabled.**

**Comment by TITC** [comment]
The problem seems solved after I changed the base model from [chilloutmix](https://civitai.com/models/6424?modelVersionId=7543) to [majicmixRealistic_v6](https://civitai.com/models/43331?modelVersionId=94640), feel free to close the issue at any time, and thanks for your time to help me solve the problem.

<img src="https://github.com/ototadana/sd-face-editor/assets/35098797/3b0f0619-09a0-42d1-b94e-8b14e708551d" width=30% height=30%>
<img src="https://github.com/ototadana/sd-face-editor/assets/35098797/162a9c07-e56e-4832-9b6a-ae9e7145e47a" width=30% height=30%>
<img src="https://github.com/ototadana/sd-face-editor/assets/35098797/103aeb7b-a710-49ec-a643-0e8a5a8acd3c" width=30% height=30%>


---


1. Information about the image on the right side (the image after Face Editor has processed it) when "Show original image" is enabled.
```
high quality, face portrait photo of 26 y.o european woman, wearing black dress, serious face, detailed face, skin pores, cinematic shot, dramatic lighting

Negative prompt: Negative prompt: (deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime), text, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck, BadDream, UnrealisticDream

Steps: 97, Sampler: DPM++ 2S a Karras, CFG scale: 7, Seed: 798713878, Size: 512x512, Model hash: a757fe8b3d, Model: chilloutmix_, Denoising strength: 0, Clip skip: 2, face_editor_enabled: True, face_editor_face_margin: 1.6, face_editor_confidence: 0.97, face_editor_strength1: 0.25, face_editor_strength2: 0, face_editor_max_face_count: 20, face_editor_mask_size: 1, face_editor_mask_blur: 3, face_editor_prompt_for_face: "", face_editor_apply_inside_mask_only: True, face_editor_apply_scripts_to_faces: False, face_editor_face_size: 512, face_editor_use_minimal_area: True, face_editor_ignore_larger_faces: True, face_editor_affected_areas: Face;Hair, face_editor_workflow: "{\n \"face_detector\": \"RetinaFace\",\n \"rules\": {\n \"then\": {\n \"face_processor\": \"img2img\",\n \"mask_generator\": {\n \"name\": \"BiSeNet\",\n \"params\": {\n \"fallback_ratio\": 0.1\n }\n }\n }\n }\n}", face_editor_upscaler: None, face_editor_tilt_adjustment_threshold: 20, Version: v1.5.1
```

2. The left image with "Show original image" enabled.
upload image->`left image`->image with face mask
<img src="https://github.com/ototadana/sd-face-editor/assets/35098797/3b0f0619-09a0-42d1-b94e-8b14e708551d" width=30% height=30%>

<img src="https://github.com/ototadana/sd-face-editor/assets/35098797/a38a193f-ab2d-47f9-a2e2-ce2316dcde4c" width=30% height=30%>

<img src="https://github.com/ototadana/sd-face-editor/assets/35098797/0d44cb8c-5a00-4882-be4d-2eb932bab423" width=30% height=30%>


3. Information displayed in the console at runtime.

```
number of faces: 1.                                                                                                                                                                     | 0/1 [00:00<?, ?it/s]
prompt for the face: high quality, face portrait photo of 26 y.o european woman, wearing black dress, serious face, detailed face, skin pores, cinematic shot, dramatic lighting

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:06<00:00,  3.69it/s]
Total progress: 26it [00:07,  3.46it/s]
Total progress: 26it [00:07,  3.60it/s]

```

4. The image generated when the Face Editor is disabled.
![00006-798713878](https://github.com/ototadana/sd-face-editor/assets/35098797/671c117f-6a9e-4ce9-8f15-d65ce429958d)
