### ISSUE TITLE
XSeg, a better mask generator

### ISSUE THREAD

**Issue by fgas453243** [ototadana/sd-face-editor#143]
Hello.
Thanks for the great extension release and the updates.

Is it possible to adopt XSeg as a better mask-generator than the one currently implemented?

XSeg is a mask generation mechanism mainly used in software called deepfacelab.
XSeg identifies faces and the rest (bangs, sunglasses, whistles, microphones, etc.) and generates a mask that does not contain non-face obstructions.
XSeg generates masks based on pre-trained models. You can train the model yourself or use the Generic-XSeg model shipped with deepfacelab. The model consists of the following 4 files.
・XSeg_256_opt.npy
・XSeg_256.npy
・XSeg_data.dat
・XSeg_default_options.npy

Here is an example using XSeg. Below is the source image.
![source](https://github.com/ototadana/sd-face-editor/assets/129657025/5c7a80ff-df0e-4819-9b8d-13eb8daf10ce)

First, fix the source image using NoMaskGenerator.
![00003-880432504 0-best quality, 4k, 8k, high quality, very high resolution, RAW photo,_1girl,_straight hair, long hair, black hair, dark purple ha](https://github.com/ototadana/sd-face-editor/assets/129657025/fc93ec0a-5042-4463-ae0f-cd7a0f35d861)

Then apply XSeg to the source image to generate the mask image.
![mask_xseg-dst](https://github.com/ototadana/sd-face-editor/assets/129657025/175708de-88cd-417f-a425-a3ede3ca3565)

Applies an XSeg mask to the fixed image.
![xseg-applied_00003-880432504 0-best quality, 4k, 8k, high quality, very high resolution, RAW photo,_1girl,_straight hair, long hair, black hair, dark purple ha](https://github.com/ototadana/sd-face-editor/assets/129657025/8cc9c1ff-5e00-4ee2-bc5f-ec9d6600c29d)

Finally merge with the source image.
![merged_00003-880432504 0-best quality, 4k, 8k, high quality, very high resolution, RAW photo,_1girl,_straight hair, long hair, black hair, dark purple ha](https://github.com/ototadana/sd-face-editor/assets/129657025/a536d2d6-c476-48e5-86f5-dc3c9887c78e)
The face is fixed and the rest looks unfixed.

For comparison, here is an example by BiSeNetMaskGenerator.
![00002-880432504 0-best quality, 4k, 8k, high quality, very high resolution, RAW photo,_1girl,_straight hair, long hair, black hair, dark purple ha](https://github.com/ototadana/sd-face-editor/assets/129657025/9794209f-b539-4b39-aaee-6404ea31d7c0)
![tmpqbewoaag](https://github.com/ototadana/sd-face-editor/assets/129657025/3a17fefa-d709-4b84-883d-eb14cdb5e022)
BiSeNetMaskGenerator can accurately identify faces, but it doesn't seem to take into account obstacles.

**Comment by ototadana** [comment]
Thanks for the interesting suggestions.

I will read the deepfacelab code to see how I can implement it.

**Comment by fgas453243** [comment]
Thank you for your reply immediately.
I'm looking forward to it.

**Comment by fgas453243** [comment]
Thank you for letting me know your progress along the way.
I look forward to implementing it.

**Comment by ototadana** [comment]
The implementation is ready.

It is available by following these steps:

1. Update to the latest version
2. In the "Settings" tab of the Face Editor section, set the following settings: 
    - Enable 'Search workflows in subdirectories'.
    - Enable 'openmmlab' option under "Additional components".
3. Restart the Web UI on the terminal.
4. select 'examples/openmmlab'  as workflow.

Please try it.

**Comment by fgas453243** [comment]
Thank you for implementing an excellent mask generator.

I tried mmseg mask generator.
![tmppe2bhhrv](https://github.com/ototadana/sd-face-editor/assets/129657025/90c89a8a-b144-40d2-bd80-6400b5fa10b0)
The face is fixed and the rest looks unfixed.

Thank you for always responding to user requests.
I look forward to the future of sd-face-editor.
Thank you.
