### ISSUE TITLE
sometimes face editor doesn't work with lora

### ISSUE THREAD

**Issue by GoldenMiocola** [ototadana/sd-face-editor#152]
![$IJ{ES`Q1I89TECL86@QCMC](https://github.com/ototadana/sd-face-editor/assets/134237710/461b040d-a021-4684-9cfe-9d5199f2d918)
dont know what happened, face editor cant detected face during using with lora, it happened often frequency.

**Comment by ototadana** [comment]
Some faces cannot be detected well by the default detector. It is particularly poor at animation-style images. In such cases, an alternative detector may be used for detection.  Please refer to: https://github.com/ototadana/sd-face-editor/issues/94#issuecomment-1614809220

**Comment by GoldenMiocola** [comment]
I remember that face editor used to work pretty well for anime faces. 😥

**Comment by ototadana** [comment]
The default detector is exactly the same one from the first version. Previous reports have shown that detection often fails when using [Counterfeit ](https://github.com/ototadana/sd-face-editor/issues/94#issuecomment-1615951691) or [Anything](https://github.com/ototadana/sd-face-editor/issues/31#issuecomment-1513050900).

This problem can be more likely avoided by incorporating a different detector into the workflow.
For more information, please see:

- https://github.com/ototadana/sd-face-editor/issues/94#issuecomment-1615951691
- https://github.com/ototadana/sd-face-editor/issues/94#issuecomment-1615948960
- https://github.com/ototadana/sd-face-editor/blob/main/README.md#workflow-editor
- https://github.com/ototadana/sd-face-editor/blob/main/workflows/examples/README.md#example-3-high-accuracy-face-detection-workflow---bingsuadetailer-example
- https://github.com/ototadana/sd-face-editor/blob/main/workflows/examples/README.md#example-4-anime-face-detection-workflow---lbpcascade_animeface-example
