### ISSUE TITLE
The output image in api can not read png info out

### ISSUE THREAD

**Issue by glovenone** [ototadana/sd-face-editor#155]
I can generate image in api, but the image info can not be read out in webui of the "PNG INFO" tab. The result is "no params"
This is the params of plugins.

   "alwayson_scripts": {
        "ControlNet": {
            "args": [
                    {"enabled": true,
                    "image": "",
                    "mask": null,
                    "module": "canny",
                    "model": "control_sd15_canny [fef5e48e]",
                    "weight": 1,
                    "invert_image": false,
                    "resize_mode": 1,
                    "rgbbgr_mode": false,
                    "lowvram": false,
                    "processor_res": 512,
                    "threshold_a": 100,
                    "threshold_b": 200,
                    "guidance": 1,
                    "guidance_start": 0,
                    "guidance_end": 1,
                    "guessmode": false}
            ]
        },
        "face editor ex": {
            "args": [
                {
                    "affected_areas": ["Face", "Hair", "Hat", "Neck"],
                    "mask_size": 10,
                    "mask_blur": 15
                }
            ]
        }

**Comment by glovenone** [comment]
<img width="2549" alt="image" src="https://github.com/ototadana/sd-face-editor/assets/584024/a5cfdacd-f275-432c-99c5-086d5b57b912">

**Comment by ototadana** [comment]
When saving images, do you explicitly specify the pnginfo parameter?

Please try the following example code, as I have confirmed that it saves correctly.

```python
import base64
import io
import json

import requests
from PIL import Image, PngImagePlugin

url = "http://127.0.0.1:7860"

payload = {
    "sampler_index": "Euler a",
    "prompt": "a boy",
    "steps": 20,
    "cfg_scale": 7,
    "width": 512,
    "height": 512,
    "alwayson_scripts": {
        "face editor ex": {
            "args": [
                {
                    "prompt_for_face": "smile",
                    "show_original_image": True,  # Recommended: Because the infotexts array contains information about the original image
                }
            ]
        },
    },
}

response = requests.post(url=f"{url}/sdapi/v1/txt2img", json=payload)
r = response.json()

for i, result in enumerate(r["images"]):
    image = Image.open(io.BytesIO(base64.b64decode(result.split(",", 1)[0])))
    pnginfo_data = PngImagePlugin.PngInfo()

    infotexts = json.loads(r["info"])["infotexts"][i]
    pnginfo_data.add_text("parameters", infotexts)
    image.save(f"output{i}.png", pnginfo=pnginfo_data)
```

**Comment by glovenone** [comment]
Yeah, the image info can be read out with the args '"show_original_image": True' ,  and can't read out without "show_original_image".   Is it the right logic？

**Comment by ototadana** [comment]
It's certainly not desirable behavior. I will look into it to see if it can be fixed.

**Comment by glovenone** [comment]
Thank you for looking into this issue. I really appreciate you taking the time to investigate and fix it.

**Comment by ototadana** [comment]
Thanks to you I was able to fix it. Please try it out.
