### ISSUE TITLE
An error occurred when starting the webui

### ISSUE THREAD

**Issue by AngeWoo** [ototadana/sd-face-editor#160]
W:\AI\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
*** Error running install.py for extension W:\AI\stable-diffusion-webui\extensions\sd-face-editor.
*** Command: "W:\AI\stable-diffusion-webui\venv\Scripts\python.exe" "W:\AI\stable-diffusion-webui\extensions\sd-face-editor\install.py"
*** Error code: 1
*** stderr: W:\AI\stable-diffusion-webui\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
***   rank_zero_deprecation(
*** Traceback (most recent call last):
***   File "W:\AI\stable-diffusion-webui\extensions\sd-face-editor\install.py", line 17, in <module>
***     if shared.opts.data.get("face_editor_additional_components", None) is not None:
*** AttributeError: 'NoneType' object has no attribute 'data'

**Comment by ototadana** [comment]
I assume you are using a pre-release version (`v1.6.0-RC` or `dev` branch) of the Web UI, in which case you will get this error.
You can avoid this error by using the [fix/install-error-in-1.6.0](https://github.com/ototadana/sd-face-editor/pull/157) branch. (When the official version 1.6.0 is released, I will merge this branch if the same error still occurs)
