### ISSUE TITLE
Blurring a face; can you set the amount of blur?

### ISSUE THREAD

**Issue by JELSTUDIO** [ototadana/sd-face-editor#163]
The code has this line:

"face_processor": "Blur"

Is it possible somewhere to set the level of blur? (More blur or less blur than the default)

Thank you.

**Comment by ototadana** [comment]
Yes. You can change it with the value of "radius".
The default value is `20`. Larger values will make the blur stronger, smaller values will make the blur weaker.

You can specify the following:

```
{
    "face_detector": "RetinaFace",
    "rules": {
        "then": {
            "face_processor": {
              "name": "Blur",
              "params": {
                "radius": 50
              }
            },
            "mask_generator": "NoMask"
        }
    }
}
```

Thank you.

**Comment by JELSTUDIO** [comment]
Works perfectly :)

Thank you very much for having added the ability to edit these work-flows.
I'm new to all of this so still have a lot to learn about how the proper syntax is.

I have given the plugin a star.
