### ISSUE TITLE
where is modules

### ISSUE THREAD

**Issue by hubo0417** [ototadana/sd-face-editor#171]
import modules.scripts as scripts
import modules.shared as shared
from modules.processing import StableDiffusionProcessing, StableDiffusionProcessingImg2Img, process_images

i can not find modules in source code，who can tell me what is the modules 
in fact i want to use source code in my project，i do not use webui，if  it only support webui?

**Comment by ototadana** [comment]
Sorry. This software is an extension of AUTOMATIC1111's Stable Diffusion Web UI.
So, the modules exist [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/tree/master/modules).
