### ISSUE TITLE
Bug: Order of operations - Face editor vs Hires Fix with a custom checkpoint

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [ototadana/sd-face-editor#173]
When using Face Editor (or something like ADetailer too), I think that it's not considering which model is used, when using the Hires Fix with a custom checkpoint for the hires steps.

![image](https://github.com/ototadana/sd-face-editor/assets/60541708/cbe0ef82-0a68-4bc6-8a4c-cd595cb7a08b)

It's using the regular checkpoint, which was used at the start of the generation instead, which means there's now a mismatch in appearance.

**Comment by ototadana** [comment]
Thanks to you I learned about such a nice option 😄 

Please try the latest version.

**Comment by MNeMoNiCuZ** [comment]
Apologies for not testing earlier.
It appears to be working! But it's overshadowed by the bug where it doesn't save any images for me.
I'll put that in as a new report.

Thanks!
