### ISSUE TITLE
Unfortunately, the previous issue has not been resolved~

### ISSUE THREAD

**Issue by gastoncao** [ototadana/sd-face-editor#178]
hey,bro:
In my previous article, I explained that when Ebsynth utility is enabled, a "Value Error: images do not match" error will occur. At that time, I thought it was caused by the different sizes of "video_mask" and "video_key", but now I have found that this is not the case. Ensuring the same size will also cause that error.

But I feel like I've found the problem and I'm not sure if it can be solved:

When Ebsynth's "Input Area" is set to "only masked" and the characters in the screen are relatively small, an error will occur. Perhaps it's because the area of Face Editor exceeds the mask range?

When I set "Input Area" to "Whole picture", an error will not occur, and the resulting image is as follows:
![00001](https://github.com/ototadana/sd-face-editor/assets/126108693/ac1b5ff7-117d-4fd9-923e-10166876d77a)
![00001](https://github.com/ototadana/sd-face-editor/assets/126108693/21aa6674-8420-41c2-bfcb-4ac571b3d72f)
The temporary solution is to only use the "Whole picture" option

**Comment by ototadana** [comment]
I was able to reproduce the same error in my environment and was able to fix it.
Please try the latest version 😃
