### ISSUE TITLE
Request for new Feature: Gaze Direction 

### ISSUE THREAD

**Issue by drdancm** [ototadana/sd-face-editor#180]
I have run into serious issues using Reactor and other Faceswap programs which your excellent program addresses directly such as distorted faces, and when the face is larger than about 50% of the image, total failure (mouth in the position of the target face, eyes all messed up with smaller eyes inside the target's eyes). No one appeared to explain why this happened, nor did anyone suggest a solution. 

So I wanted to say Congrats and a huge **THANKS!**

Another less frequent problem with the much improved and excellent job that Gourieff's Reactor has done, is that there are sometimes problems with is the direction of gaze. The target maybe looking to the side, but the swapped result has the resulting image looking forward.  

I just installed your sd-face-editor program and have not tested it, but from reading your page I think, and I may be mistaken, that your program does not specifically correct gaze direction. So, if you are looking for another issue to fix, that would be absolutely wonderful.
Perhaps this problem only surfaces with face swapping.

**Thanks Again for brilliant work!**

**Comment by ototadana** [comment]
Thank you for your request.

This software is designed to modify the detected faces using img2img. Therefore, as you can see from the images in [the README](https://github.com/ototadana/sd-face-editor/blob/main/README.md), the problem of different gazes is unlikely to occur in principle.

I believe that the gaze problem is a problem that occurs only in software that performs face swapping. However, this software does not yet have the feature to swap faces.

So, I think it would be a quicker solution if this problem were submitted not here, but to software that already has the ability to swap faces, such as Gourieff's Reactor.

Thanks.

**Comment by drdancm** [comment]
Thank you for the rapid response and I will bring this matter up at Reactor.

I do however have another question to which I have not found an answer.  Why is it that the more a face approaches a profile, and this is especially bad for profiles, both face recognition, and face swapping gets very poor?

Is this a result of the prerequisite tools that everyone uses? Perhaps the initial training was never done with face profiles? Or something else.

Thanks.
