### ISSUE TITLE
Py Deprecation Warning

### ISSUE THREAD

**Issue by drdancm** [ototadana/sd-face-editor#183]
I am running A1111 in Stability Matrix. Is this something that you are able to fix?
Or should I post this at Stability Matrix ?

Installing requirements for Face Editor
D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\extensions\sd-webui-controlnet\install.py:3: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
D:\STABLEDIFF\Data\Packages\stable-diffusion-webui\extensions\sd-webui-faceswaplab\install.py:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html

Thank You !

**Comment by ototadana** [comment]
This error is not from Face Editor, but from sd-webui-controlnet and sd-webui-faceswaplab, so I think you should contact them 😃

**Comment by drdancm** [comment]
Thank you !
