### ISSUE TITLE
 Batch processing can only process the first image

### ISSUE THREAD

**Issue by Datou** [ototadana/sd-face-editor#22]
Here is the error message:
Will process 427 images, creating 1 new images for each.
number of faces: 1
100%|██████████████████████████████████████████████████████████████████████████████████| 11/11 [00:01<00:00,  9.95it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:01<00:00,  8.94it/s]
Total progress:   0%|▎                                                               | 20/4697 [00:02<11:01,  7.07it/s]
Error completing request                                                             | 20/4697 [00:02<09:22,  8.31it/s]
Arguments: ('task(ayh262ahoqxe51x)', 5, 'oilpaint,Sexy Dakotaskye smiling at you, (night-time:1.4) rave, (realistic face:1.3), (long hair),(Busty:1.3),(underboob:1.2), tight abs, (navel piercing:1.2), dancing on stage,low cut latex hotpants, cameltoe, perfect body, deep tan, happy expression, hand on hip, High Contrast, volumetric lighting, candid, Photograph, high resolution, 4k, 8k, Bokeh,((white sports bra)),((white shoes)),((black pants))', '3d, cartoon, anime, sketches, (worst quality:2), (low quality:2), (normal quality:2), low-res, normal quality, ((monochrome)), ((grayscale)), skin spots, acne, skin blemishes, bad anatomy, ((child)) ((loli)), tattoos, bad_prompt_version2, ng_deepnegative_v1_75t, (asian.1.2) bad-hands-5, handbag, Poorly drawn hands, ((too many fingers)), ((bad fingers)) bad-image-v2-39000,((nsfw)),naked,nude,breast,((Gloves)),((t-shirt)),((shirt))\n', [], <PIL.Image.Image image mode=RGBA size=540x960 at 0x1D3016CD8D0>, None, None, None, None, None, None, 27, 16, 4, 0, 1, False, False, 1, 1, 6.5, 1.5, 0.85, 4128014353.0, -1.0, 0, 0, 0, False, 960, 540, 0, 0, 32, 0, 'F:\\序列帧\\dance-out', 'F:\\序列帧\\dance-out-face', '', [], 1, False, 7, 100, 'Constant', 0, 'Constant', 0, 4, <scripts.external_code.ControlNetUnit object at 0x000001D30B4EB610>, <scripts.external_code.ControlNetUnit object at 0x000001D30B4E8520>, <scripts.external_code.ControlNetUnit object at 0x000001D30B4E8A00>, <scripts.external_code.ControlNetUnit object at 0x000001D30B4E8610>, <scripts.external_code.ControlNetUnit object at 0x000001D30B4EAB60>, False, False, 'Horizontal', '1,1', '0.2', False, False, False, 'Attention', False, 1.6, 0.97, 0.4, 0.3, 1, 0, 0, '', False, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', 'None', '', '', 1, 'FirstGen', False, False, 'InputFrame', False,   1 2 3
0      , False, '', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '', '', 20.0, '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, None, False, None, False, None, False, None, False, 50) {}
Traceback (most recent call last):
  File "F:\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "F:\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "F:\stable-diffusion-webui\modules\img2img.py", line 166, in img2img
    process_batch(p, img2img_batch_input_dir, img2img_batch_output_dir, img2img_batch_inpaint_mask_dir, args)
  File "F:\stable-diffusion-webui\modules\img2img.py", line 76, in process_batch
    if processed_image.mode == 'RGBA':
AttributeError: 'numpy.ndarray' object has no attribute 'mode'
![image](https://user-images.githubusercontent.com/15013/232194315-05138667-f874-4ffb-9674-35809ea7014c.png)
![image](https://user-images.githubusercontent.com/15013/232194489-2f92e2b2-69b8-434b-a9e4-a1f5dc18c36b.png)

**Comment by k52252467** [comment]
Hi, I'm having the same problem, it doesn't seem to work with the bulk function in I2I, hope you can fix it

**Comment by ototadana** [comment]
@Datou @k52252467 
Thanks for reporting the error.
I have added a process to prevent errors in batch processing, please try the new version.

**Comment by Datou** [comment]
![image](https://user-images.githubusercontent.com/15013/232274669-084603e5-6a3c-4ec2-9933-d505e8c04ead.png)
Batch succeeded! You are amazing!

**Comment by k52252467** [comment]
Great, ready to use
