### ISSUE TITLE
great work, is the pipeline available to diffusers?

### ISSUE THREAD

**Issue by marvin521** [ototadana/sd-face-editor#32]
many imgs generated by diffusers also suffer the problem of distorted face, wanna use this tool in diffusers

**Comment by ototadana** [comment]
@marvin521 
It is not usable as is, but it may be possible to rewrite this script for diffusers.
I have very little experience with diffusers and would need a long time if I tried to do this. However, if someone is familiar with diffusers and python, I believe it can be accomplished in a short time.
