### ISSUE TITLE
Why repair the face is not a mask area, but a square area

### ISSUE THREAD

**Issue by tunxin** [ototadana/sd-face-editor#33]
Why is my facial repair not a face repair inside a mask, but a square area repair? It feels like pressing a square layer on top of the original image.

**Comment by tunxin** [comment]
When the denoising intensity of the face image and the overall image is inconsistent, the fix is that the body and face on the screen are inconsistent in a square appearance.

**Comment by tunxin** [comment]
When the denoising intensity of the face image is inconsistent with the overall image, when repairing the face, the entire square area near the face and the face is repaired, resulting in inconsistency with the body and is very obtrusive

**Comment by k52252467** [comment]
Please change this function to a circle, otherwise there will sometimes be obvious traces of modification at the 4 corners of the square

**Comment by ototadana** [comment]
@tunxin @k52252467 
Thanks for the feedback.
I added an "Apply inside mask only" option.
Please try it.
