### ISSUE TITLE
Problems associated with variation seeds in batch generating images

### ISSUE THREAD

**Issue by Papazi91** [ototadana/sd-face-editor#36]
When I use batch image generation with the variation seeds turned on, the variation seeds contained in the generated image information should be incremented by plus one. However, when I open the face editor plugin, the variation seeds for the batch generated images are all the first value set and are not incremented.
![aaaaa](https://user-images.githubusercontent.com/131588660/233834997-24a0db1b-45df-45d6-9726-f698a5e6faea.png)
for example, my variation seeds start at 4012764026 and I batch generate 8 images. In the PNG info shows the variation seeds should be 4012764026-4012764033, this is what it looks like when I'm not using the face editor. when I use face editor, all images variation seeds show in the PNG info will be 4012764026.

**Comment by ototadana** [comment]
@Papazi91 
Thanks for the feedback :smiley: 
I fixed it, please try the new version.
