### ISSUE TITLE
Why img to img cannot use batch count >1 ?

### ISSUE THREAD

**Issue by timmyhk852** [ototadana/sd-face-editor#39]
whenever I use this script, I can only generate 1 picture from img to img?
Is this a bug?

**Comment by ototadana** [comment]
@timmyhk852 
Thanks for using this script :smiley: 

Rather than being a 'bug,' the issue stems from the feature 'not being implemented'. The reason is that when using this script for img2img with a batch count greater than 1, I couldn't envision the desired outcome, and as a result, I didn't know how to implement it properly.

If you can provide as much specific information as possible about the following, there's a chance I can come up with an implementation:

- What specific settings ("batch count", "batch size", etc.) do you want to use?
- What is the desired outcome?

**Comment by timmyhk852** [comment]
hi, I usually set batch count as 3-5, batch size 1
The desired outcome is equal to the quality from txttoimg

**Comment by timmyhk852** [comment]
also, may I know what setting to be used to eliminate the square box around the face?

**Comment by ototadana** [comment]
@timmyhk852 
> also, may I know what setting to be used to eliminate the square box around the face?

Check "[Apply inside mask only](https://github.com/ototadana/sd-face-editor#apply-inside-mask-only)" or set a larger value for "[Denoising strength for the entire image](https://github.com/ototadana/sd-face-editor#denoising-strength-for-the-entire-image-00-10)".

**Comment by ototadana** [comment]
@timmyhk852 

> The desired outcome is equal to the quality from txttoimg

Please allow me to confirm this in case there is any misunderstanding. I understood that your request is "to generate multiple images with different seeds based on a single image". If so, I think "txt2img + ControlNet" could be used for the same purpose, but you do not want to use that one?

**Comment by timmyhk852** [comment]
oh you are right I am actually use txt2img + controlnet (drag the same image) to generate other images

**Comment by ototadana** [comment]
@timmyhk852 
Thanks to you I now know how to implement it :smiley:  
Please try the new version.

**Comment by timmyhk852** [comment]
thanks for update, another issue may be, when I use openpose together with your script, the face editing seems not working. Is that the case?

**Comment by ototadana** [comment]
@timmyhk852 
Thanks for checking. Regarding the "not working" question, can you tell me about the following:
- The specific conditions under which it occurs (e.g., number of batch counts)
- What happened when it occurred (e.g., specific error messages)

**Comment by timmyhk852** [comment]
When I use openpose with your script, the final picture is fine, but the preview picture still shows the ugly version. The fine picture is not showing in the preview section. Only showing openpose structure pictures

**Comment by ototadana** [comment]
@timmyhk852 
Thanks for the info. I have fixed the preview showing. Could you please try the new version?
