### ISSUE TITLE
another batch problem

### ISSUE THREAD

**Issue by figurehunt** [ototadana/sd-face-editor#41]
Hi there, 
I like your script, it works greater than another previous face swap script. 
But when i try to use the batch functrion in i2i, after filled in the input directory, output directory, it can't generate even one image. 
it showed "ValueError: operands could not be broadcast together with shapes (396,396,4) (396,396,3)"

i mean for example, i have 10 different images needed to change the faces. and i dont want to change it one by one by clicking the same setting. 
please help! thank you!

**Comment by ototadana** [comment]
@figurehunt 
Thanks for using this script :heart: 
Unfortunately I could not reproduce the same error in my environment.
Can you please give me a traceback so I can see where in the script the error is occurring?

**Comment by figurehunt** [comment]
i used two LoRAs, an openpose controlnet, and the face editor script, in the i2i.
it is ok for a single image. but when i use the batch function in i2i, it shown

Traceback (most recent call last):
  File "C:\AI\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\AI\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\AI\modules\img2img.py", line 166, in img2img
    process_batch(p, img2img_batch_input_dir, img2img_batch_output_dir, img2img_batch_inpaint_mask_dir, args)
  File "C:\AI\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 25, in img2img_process_batch_hijack
    return getattr(img2img, '__controlnet_original_process_batch')(p, *args, **kwargs)
  File "C:\AI\modules\img2img.py", line 63, in process_batch
    proc = modules.scripts.scripts_img2img.run(p, *args)
  File "C:\AI\modules\scripts.py", line 407, in run
    processed = script.run(p, *script_args)
  File "C:\AI\extensions\sd-face-editor\scripts\face_editor.py", line 192, in run
    return self.__proc_image(o, mask_model, detection_model,
  File "C:\AI\extensions\sd-face-editor\scripts\face_editor.py", line 307, in __proc_image
    face_bg = (face_background *
ValueError: operands could not be broadcast together with shapes (432,432,4) (432,432,3) 
提示：Python 运行时抛出了一个异常。请检查疑难解答页面。

**Comment by ototadana** [comment]
@figurehunt 
Thanks for the detailed information.
Unfortunately, I could not reproduce the same error, but I added some code that may avoid the error from occurring.
Could you please check the operation with the new version?

**Comment by figurehunt** [comment]
Thanks for your help and the update! it works now

**Comment by figurehunt** [comment]
by the way, while the faces went in sequence, (yes, i try to change the face in a short video), i found the position of eyes and nose seemed not that stable, even when i used an openpose for face. 
so i am wondering whether openpose would work in the face-changing process or not. 
if not, it will be great to read the openpose-face data to stablize the face.

**Comment by cindylaii** [comment]
Earlier today, due to this issue, I had to manually upload the images one by one. Now that you have fixed it, I am glad and thankful for your help. I also wanted to let you know that the effect of your script is really great.

**Comment by ototadana** [comment]
@figurehunt 
An "Apply scripts to faces" option has been added to allow ControlNet to be applied when generating face images.

However, care must be taken when using this option: the ControlNet input image must be specified only in img2img, and nothing must be specified in the ControlNet panel. (For batch processing, specify only the "Input directory" in img2img; leave the "Input Directory" in the ControlNet panel empty.) Specifying it in the ControlNet panel will completely collapse the image.

Please try it!

**Comment by figurehunt** [comment]
hi @ototadana sorry for the late reply! 
it is more stable than before now. thanks for your great work!
and thanks for your remind about the controlnet input stuff, i seldom use this input actually.
i will open another issue for other maybe problem
