### ISSUE TITLE
denoising problem

### ISSUE THREAD

**Issue by figurehunt** [ototadana/sd-face-editor#46]
Hi, it's me again

I used to use i2i to change the style and the face, and now I found there are 3 denoising happening during the process, and most of the time it will change the details I preferred beside the face. so I am wondering whether you could merge some functions so that it won't affect too much of the area.

3 denosing:
the first one is the basic one in i2i. I think it will affect the whole image.
the other two are from the script of face editor. 
I have 2 questions:
1.Denoising feature on the face is surely needed. but does it work on the original image I firstly put into i2i? or It works after i2i changed the image, since I found two images in the output. one of them seems the normal output of i2i.

2.from the description I found the 2nd denoising is to make the new face fit for the other parts, but it also change the other details beside the face. therefore I am wondering is it possible to make it works only for the margin beside the face? and could it be merged with the 1st face-demosing together and make the new face the margin at the same time?

Thanks for your work in advanced! Good day!

**Comment by ototadana** [comment]
@figurehunt 
Hi, 
I will answer your question.

> the first one is the basic one in i2i. I think it will affect the whole image.

This only works when the "Apply scripts to faces" option is enabled.

> 1.Denoising feature on the face is surely needed. but does it work on the original image I firstly put into i2i? or It works after i2i changed the image, since I found two images in the output. one of them seems the normal output of i2i.

"Apply scripts to faces" option, if enabled, works on images created by the first denoising. Otherwise, it works on the original image.

> 2.from the description I found the 2nd denoising is to make the new face fit for the other parts, but it also change the other details beside the face. therefore I am wondering is it possible to make it works only for the margin beside the face? and could it be merged with the 1st face-demosing together and make the new face the margin at the same time?

I think you can get close to what you want by enabling the "Apply inside mask only" option and setting the value of "Denoising strength for the entire image" to as low a value as possible (in some cases it may be ok to set it to 0). 

Please give it a try!

**Comment by figurehunt** [comment]
okok, I got it. It is helpful! 
I will try on different value. Thanks!

**Comment by zzxxccii** [comment]
> Apply script to faces

what the difference of "Apply script to faces" enabled or not  😘

**Comment by ototadana** [comment]
@zzxxccii 
Sorry I have not documented that option.

Please see here:
- https://github.com/ototadana/sd-face-editor/issues/41#issuecomment-1537340496
- https://github.com/ototadana/sd-face-editor/issues/41#issuecomment-1537545650

**Comment by ototadana** [comment]
> I think you can get close to what you want by enabling the "Apply inside mask only" option and setting the value of "Denoising strength for the entire image" to as low a value as possible (in some cases it may be ok to set it to 0).

Default values have been changed and readme updated.
