### ISSUE TITLE
Control Net Reference Only, cannot save pics

### ISSUE THREAD

**Issue by timmyhk852** [ototadana/sd-face-editor#51]
I use your updated version with control net reference only, but the picture is not saved in my folder

**Comment by ototadana** [comment]
@timmyhk852 
Neither of the two problems you reported could be reproduced in my environment.
Can you give me more details about the operations you performed, settings, etc.? Also, if you are getting errors in the console, please let me know that as well.

**Comment by werran2** [comment]
> 

same here, can not save img 2 img pics.

Error completing request
Arguments: ('{"prompt": "danae \\\\(character\\\\),1girl, best quality, masterpiece, illustration, an extremely delicate and beautiful, extremely detailed ,CG ,unity ,8k wallpaper, (realistic, photo-realistic:1.37),Amazing, finely detail, <lora:Danae28_multires-000005:1>", "all_prompts": ["danae \\\\(character\\\\),1girl, best quality, masterpiece, illustration, an extremely delicate and beautiful, extremely detailed ,CG ,unity ,8k wallpaper, (realistic, photo-realistic:1.37),Amazing, finely detail, <lora:Danae28_multires-000005:1>"], "negative_prompt": "(worst quality:2), (low quality:2), (normal quality:2), lowres, ((monochrome)), ((grayscale)),paintings, sketches, skin blemishes, bad anatomy,tilted head, multiple girls,bad hands, text, error, missing fingers,extra digit, fewer digits, blurry,bad feet,poorly drawn hands,poorly drawn face,mutation,deformed,jpeg artifacts,signature,watermark,extra fingers,extra arms,extra legs,malformed limbs,fused fingers,too many fingers,cross-eyed,mutated hands,bad body,bad proportions,gross, ng_deepnegative_v1_75t", "all_negative_prompts": ["(worst quality:2), (low quality:2), (normal quality:2), lowres, ((monochrome)), ((grayscale)),paintings, sketches, skin blemishes, bad anatomy,tilted head, multiple girls,bad hands, text, error, missing fingers,extra digit, fewer digits, blurry,bad feet,poorly drawn hands,poorly drawn face,mutation,deformed,jpeg artifacts,signature,watermark,extra fingers,extra arms,extra legs,malformed limbs,fused fingers,too many fingers,cross-eyed,mutated hands,bad body,bad proportions,gross, ng_deepnegative_v1_75t"], "seed": 2466413225, "all_seeds": [2466413225], "subseed": 1687289444, "all_subseeds": [1687289444], "subseed_strength": 0, "width": 1080, "height": 1354, "sampler_name": "DPM++ SDE Karras", "cfg_scale": 7, "steps": 20, "batch_size": 1, "restore_faces": false, "face_restoration_model": null, "sd_model_hash": "bbf07e3a1c", "seed_resize_from_w": 0, "seed_resize_from_h": 0, "denoising_strength": 0.4, "extra_generation_params": {}, "index_of_first_image": 0, "infotexts": ["danae \\\\(character\\\\),1girl, best quality, masterpiece, illustration, an extremely delicate and beautiful, extremely detailed ,CG ,unity ,8k wallpaper, (realistic, photo-realistic:1.37),Amazing, finely detail, <lora:Danae28_multires-000005:1>\\nNegative prompt: (worst quality:2), (low quality:2), (normal quality:2), lowres, ((monochrome)), ((grayscale)),paintings, sketches, skin blemishes, bad anatomy,tilted head, multiple girls,bad hands, text, error, missing fingers,extra digit, fewer digits, blurry,bad feet,poorly drawn hands,poorly drawn face,mutation,deformed,jpeg artifacts,signature,watermark,extra fingers,extra arms,extra legs,malformed limbs,fused fingers,too many fingers,cross-eyed,mutated hands,bad body,bad proportions,gross, ng_deepnegative_v1_75t\\nSteps: 20, Sampler: DPM++ SDE Karras, CFG scale: 7, Seed: 2466413225, Size: 1080x1354, Model hash: bbf07e3a1c, Model: basil mix, Denoising strength: 0.4, ENSD: 31337"], "styles": [], "job_timestamp": "20230521154125", "clip_skip": 1, "is_using_inpainting_conditioning": false}', [{'name': 'C:\\Users\\Werran\\AppData\\Local\\Temp\\tmp3_ble2rd.png', 'data': 'http://127.0.0.1:7860/file=C:\\Users\\Werran\\AppData\\Local\\Temp\\tmp3_ble2rd.png', 'is_file': True}, {'name': 'C:\\Users\\Werran\\AppData\\Local\\Temp\\tmpe0ca68kg.png', 'data': 'http://127.0.0.1:7860/file=C:\\Users\\Werran\\AppData\\Local\\Temp\\tmpe0ca68kg.png', 'is_file': True}], False, 1) {}
Traceback (most recent call last):
  File "C:\novelai-webui-aki-v3\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\novelai-webui-aki-v3\modules\ui_common.py", line 73, in save_files
    fullfn, txt_fullfn = modules.images.save_image(image, path, "", seed=p.all_seeds[i], prompt=p.all_prompts[i], extension=extension, info=p.infotexts[image_index], grid=is_grid, p=p, save_to_dirs=save_to_dirs)
IndexError: list index out of range

**Comment by ototadana** [comment]
@werran2 
Thanks for the info :heavy_heart_exclamation: 

You have helped me identify the problem.
I have fixed the problem, please try the latest version.
