### ISSUE TITLE
scaling by factor miscalculates dimension

### ISSUE THREAD

**Issue by fanyangto** [ototadana/sd-face-editor#52]
When scaling a picture of 1280x720 by a factor 2, the resulting dimension is 2560x1472 (not 1440). This slight change in aspect ratio affect the face shape. 

But when I choose custom dimension and enter 2560 and 1440 respectively, the result is perfect. 

Please check and this must be an easy fix. It's a great extension.

**Comment by ototadana** [comment]
@fanyangto 
Thanks for using this script.
Can you please tell me the specific operation so that I can reproduce the phenomenon?

**Comment by fanyangto** [comment]
My apology, I open the ticket under a wrong place. It's for a different extension. 
I am really sorry. :-(. We should close this one now.

**Comment by fanyangto** [comment]
Wrongly reported.
