### ISSUE TITLE
How to use the extension in 'stable-diffusion-webui-api'?

### ISSUE THREAD

**Issue by TyroneZhang** [ototadana/sd-face-editor#57]
we deploy the webUI in aws service, how how invoke the face-editor extension with api, such as controlnet :
`'img2img_payload': {
        'init_images': [
            encode_image_to_base64(image)
        ],
        'enable_hr': False, 
        'denoising_strength': 0.7, 
        'firstphase_width': 0, 
        'firstphase_height': 0, 
        'prompt': 'masterpiece, best quality, ultra-detailed', 
        'styles': [''], 
        'seed': -1.0, 
        'subseed': -1.0, 
        'subseed_strength': 0, 
        'seed_resize_from_h': 0, 
        'seed_resize_from_w': 0, 
        'sampler_index': 'DPM++ 2S a Karras', 
        'batch_size': 1, 
        'n_iter': 1,
        'steps': 50, 
        'cfg_scale': 7, 
        'width': 640, 
        'height': 1024, 
        'restore_faces': False, 
        'tiling': False, 
        'negative_prompt': 'nsfw, lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts,signature, watermark, username, blurry, artist name', 
        's_churn': 0, 
        's_tmax': None, 
        's_tmin': 0, 
        's_noise': 1, 
        'clip_skip': 1,
        'alwayson_scripts': {
            "controlnet": {
                "args": [
                    {
                        'enabled':True,
                        'image': encode_image_to_base64(image),
                        'model': 'control_sd15_hed [fef5e48e]',
                        'weight': 0.55,
                        'processor_res': 640,
                        'guidance_start': 0,
                        'guidance_end': 0.7,
                        'threshold_a': 100, # default
                        'threshold_b': 200, # default
                        'guess_mode': False,
                        'module': 'none',
                        'low_vram': False,
                        'eta': 1,
                        #'mask: '',
                    },
                    {
                        'enabled':True,
                        'image': encode_image_to_base64(image),
                        'model': 'control_sd15_openpose [fef5e48e]',
                        'weight': 1,
                        'processor_res': 640,
                        'guidance_start': 0,
                        'guidance_end': 0.8,
                        'guidance': 1,
                        'threshold_a': 100, # default
                        'threshold_b': 200, # default
                        'guessmode': False,
                        'module': 'none',
                        'low_vram': False,
                        'eta': 1,
                        #'mask: '',
                    },
                    {
                    "enabled": False,
                    }
                ]
            }
        }`

**Comment by ototadana** [comment]
@TyroneZhang 
Thanks for the feedback.

I have made a few modifications to allow API calls.
Try using the latest version and specify "face editor ex" in the script name as follows:

```
    "alwayson_scripts": {
        "face editor ex": {
            "args": [{"apply_inside_mask_only": False, "prompt_for_face": "smile"}]
        },
```

**Comment by TyroneZhang** [comment]
@betogaona7 
Thanks for support the api feature.
It works!
