### ISSUE TITLE
Where is the picture before face editor working

### ISSUE THREAD

**Issue by DuroCuri** [ototadana/sd-face-editor#59]
As I generate 250 batches, batch size 8 pictures, total 2000 pictures, face editor will work after all pictures are generated. But the RAM will continously increase until out of ram. Where can I find these pictures before face editor process, thank you for your generious contribution!
![image](https://github.com/ototadana/sd-face-editor/assets/118010803/3b915bb9-ad41-42dd-a06b-73b4e8ec62a8)

**Comment by ototadana** [comment]
@DuroCuri 
Thanks for using this script.
["Save original image"](https://github.com/ototadana/sd-face-editor#save-original-image) option can be enabled to save the image before modification.

**Comment by DuroCuri** [comment]
Thank you!
