### ISSUE TITLE
[Feature Request] save face editor info to generated png EXIF 

### ISSUE THREAD

**Issue by JoeyLearnsToCode** [ototadana/sd-face-editor#69]
把face editor里的参数保存到生成的图片的EXIF信息中。
并且反过来，也允许从png EXIF中还原参数到face editor（点“发送到文生图”的时候）。
这样能让face editor生成的图片可以重复还原，就像[sd-webui-additional-networks](https://github.com/kohya-ss/sd-webui-additional-networks)那样。

Save the parameters in the face editor to the EXIF ​​information of the generated picture.
And, allow to restore parameters from png EXIF ​​to face editor (when "send to text2img").
This allows the images generated by the face editor to be restored repeatedly, just like [sd-webui-additional-networks](https://github.com/kohya-ss/sd-webui-additional-networks) did.

**Comment by ototadana** [comment]
Thanks for the feedback.
I too thought it would be useful to be able to do this :smiley: 
I have added the feature and hope you will try it.
