### ISSUE TITLE
Batch processing function

### ISSUE THREAD

**Issue by amytong85** [ototadana/sd-face-editor#7]
I really like this script, but it can only handle one image at a time. When I generate like 100 large images at once, all faces may need to be repaired. I wish this script can be placed on the txt2img tab and repair faces while generating them, which will be more useful.
Thanks for your outstanding work。

**Comment by ototadana** [comment]
@amytong85  Thanks for your feedback :smiley: 
It is now possible to add to txt2img!

**Comment by amytong85** [comment]
I‘m sorry to trouble you,but it still have a problem,using face edit script in t2i reduced the image quality. May be some problem with hiresfix? Those images using all the same settings,but txt2img file size are only 1.3Mb,the original file are 1.8Mb.
![i2i+faceedit](https://user-images.githubusercontent.com/126079848/230825386-604ca0f6-5f9a-4e4f-b535-0e4090986c07.png)
![t2i+faceedit](https://user-images.githubusercontent.com/126079848/230825399-18c8c6c3-66c5-4445-9fbf-6038496b400e.png)
![original](https://user-images.githubusercontent.com/126079848/230825406-1fada0c9-bc32-48dd-8ded-908c048dc082.png)

**Comment by ototadana** [comment]
Thanks for using it so quickly and giving me feedback :smiley: 
As for the hires fix, it was an omission and has been fixed.
And thanks for the very beautiful images :heart:

**Comment by amytong85** [comment]
Hello its me again!
There is a problem with output files,i generated about 1k images,now my output folder is sorted like original 1,fixied 1,original 2,fixed 2 and so on,no way to easily pick out fixed images.
I have two ideas. One is to add options to decide whether or not to keep the original image in t2i, and the other is to add words like original and fixed to the file names, so that I can search to find what i want.
Forgive me for my poor English and thanks again.

**Comment by amytong85** [comment]
you still working for this？

**Comment by ototadana** [comment]
@amytong85 
Sorry for the late reply.
In response to your suggestion, I am adding a "save original image" option.
I am now doing final testing and will be able to release it soon.

**Comment by ototadana** [comment]
@amytong85 
Sorry for the lack of explanation, the img2img tab had an error and I had to cancel it in a hurry :sweat_smile: 
Fixes have been completed!

**Comment by k52252467** [comment]
Hi, it doesn't seem to work with the bulk function in I2I, hope you can fix it

**Comment by k52252467** [comment]
Great, ready to use
