### ISSUE TITLE
Can wildcard support be added?

### ISSUE THREAD

**Issue by Gh20221205** [ototadana/sd-face-editor#79]
Face editor works great especially in group picture. I wonder if wildcard support can be added to the prompt of face editor so that each face could have different expression. Thank you.

**Comment by ototadana** [comment]
@Gh20221205 
Thanks for the suggestion of additional features! To avoid misunderstandings, could you give me some prompt examples and what images should be created by it?

**Comment by Gh20221205** [comment]
> @Gh20221205 Thanks for the suggestion of additional features! To avoid misunderstandings, could you give me some prompt examples and what images should be created by it?

Firstly I have wildcards extension installed.
https://github.com/AUTOMATIC1111/stable-diffusion-webui-wildcards
This allows me to use random text from a txt file saved in wildcards folder in that extension as the main prompt. I wish the same can be supported at face editor's prompt.

For example, I have an expression.txt saved in wildcards folder with a list of different expressions in it. To use wildcards, just put __expression__, in prompt, it will be replaced by a random expression from the list. For face editor, I suppose each face can be prompted with a random expression. I hope I explained my request clear enough. BTW, I use face editor with multiple girls group lora.
https://civitai.com/models/51136/multiple-girls-group

**Comment by ototadana** [comment]
@Gh20221205 
Thanks for sharing the details.
It sounds like a very interesting feature :smiley: 
I think I understand your request and will try to implement it.

**Comment by Gh20221205** [comment]
> @Gh20221205 Thanks for sharing the details. It sounds like a very interesting feature 😃 I think I understand your request and will try to implement it.

Thanks so much. I think the ultimate goal is to output different face for each face detected, it will be better than different expressions of the same face.

**Comment by ototadana** [comment]
@Gh20221205 
Now I have added wildcard support.
One more thing, I added the ability to specify prompts separated by `||` to control faces individually.

Please refer to the [README](https://github.com/ototadana/sd-face-editor#change-facial-expression) for details.
Thanks to your ideas, I have created quite a fun image :heavy_heart_exclamation:

**Comment by Gh20221205** [comment]
> @Gh20221205 Now I have added wildcard support. One more thing, I added the ability to specify prompts separated by `||` to control faces individually.
> 
> Please refer to the [README](https://github.com/ototadana/sd-face-editor#individual-instructions-for-multiple-faces) for details. Thanks to your ideas, I have created quite a fun image ❣️

Awesome! To make it more fun, is it possible to add an option to allow user to choose between random or sequential order when the string is picked from the txt file? For example, `ll` means random, `@@` means sequential, i.e., picking the string from the first row to last? It's just a thought, you might have better idea to have this sequential order implemented. Thanks again!

**Comment by ototadana** [comment]
@Gh20221205 

Thanks for the feedback.

As for whether you want random or sequential order, you can control it in the following ways:

- If you want to select expressions sequentially, use `||` in "Prompt for face" without wildcards, as in the example given in the [README](https://github.com/ototadana/sd-face-editor#individual-instructions-for-multiple-faces).
- If you want a random selection, do not use `||`, but use wildcards only. For example, in "Prompt for face" put `__test1__` and in the file `test1.txt` put the following to make a random selection.

  ```
  snow white
  smile
  sad clone
  ```

  Make sure that the "Use same seed for all images" option is disabled in the Wildcards Extension settings.

Please try it!
