### ISSUE TITLE
Is there a way to use it in Extras?

### ISSUE THREAD

**Issue by aidec** [ototadana/sd-face-editor#87]
Sometimes I just want to easily swap faces in an original image. 
Using img2img generation is much slower than using Extra. 
So I'm wondering if this feature can be used in Extras?

**Comment by aidec** [comment]
Thank you for your prompt reply. What I meant was that in Extras, it only applies an upscaling algorithm, while img2img performs a full redraw of the entire image at the same size. Extras is faster in such cases, as sometimes I only want to trigger the face editor on the original image to make adjustments to the face.

However, I tested it myself yesterday and it seems that by setting the Denoising strength to 0 in img2img, I can achieve the same effect as Extras.

Thank you again for your response.

**Comment by ototadana** [comment]
Thanks for the detailed explanation.

It is true that if oune wants to change only the face, the img2img process for the whole image itself is unnecessary. I will update the README with the information you provided.

Thank you very much for this very useful suggestion for all users.

**Comment by ototadana** [comment]
[README](https://github.com/ototadana/sd-face-editor#fixing-images-that-already-exist) has been improved :smiley:

**Comment by aidec** [comment]
awesome!!
