### ISSUE TITLE
"Prompt for face" for lora

### ISSUE THREAD

**Issue by xuechengjinxiu** [ototadana/sd-face-editor#93]
I want to use "Prompt for face" option for lora to generate one custom face, but lora prompt have no effect.

**Comment by ototadana** [comment]
@xuechengjinxiu 

Thanks for using this script.

I have tried it on several lora and it seems to work fine.

Maybe the effect is just weak, so the following settings may help.

- lora description in the form of `<lora:lorafilename:multiplier>` and increase the multiplier value (e.g. 1.5)
- Increase the value of "Advanced Options - (3) Recreate the Faces - Denoising strength for face images" (e.g. 0.5)

Please try it!
