### ISSUE TITLE
Face not detected with this lora

### ISSUE THREAD

**Issue by Gh20221205** [ototadana/sd-face-editor#94]
I tried to use face editor with [this lora](https://civitai.com/models/86633), somehow face editor failed to detect face properly in the image generated. Sometimes it only detects 1 face, other times it wont detect any face even when I can see there are three faces. The face detection confidence has been set at 0.7, checked the box Use minimal area (for close faces), but it doesn't help. Tried restarting webui and reinstall of face editor, no luck. Maybe it's due to these faces are too close to each other? As a comparison, Adetailer detects faces correctly.

Here's the prompt used for testing

`masterpiece,  (RAW photo, best quality), formal art, photo-realistic,
1girl,
 <lora:threeheads-v1:1> (3head, three heads:1.5) `

**Comment by ototadana** [comment]
Thanks for the feedback.

I recognize that there are some faces that cannot be detected. 

To avoid the hassle of installing additional software, I have been using https://github.com/xinntao/facexlib, which is also used by stable-diffusion-webui, to detect faces. However, I am looking into other means of face detection to solve this problem. If you know of a better face detection or face segmentation model, please let me know!

**Comment by Gh20221205** [comment]
> Thanks for the feedback.
> 
> I recognize that there are some faces that cannot be detected.
> 
> To avoid the hassle of installing additional software, I have been using https://github.com/xinntao/facexlib, which is also used by stable-diffusion-webui, to detect faces. However, I am looking into other means of face detection to solve this problem. If you know of a better face detection or face segmentation model, please let me know!
Adetailer uses ultralytics to detect faces.
https://github.com/ultralytics/ultralytics

**Comment by Emersonksc** [comment]
I also met the same problem with this [lora](https://civitai.com/models/73305/zyd232s-ink-style), despite not the same lora.
webui:1.4; sd face editor: 0.93
below are webui arguments
1 girl, yellow hair, big eyes, closed mouth, sad, portrait, <lora:zyd232_ChineseInkStyle_v1_0:1>
Negative prompt: easynegative
Steps: 20, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 3311024160, Size: 512x512, Model hash: cbfba64e66, Model: CounterfeitV30_v30, Clip skip: 2, Lora hashes: "zyd232_ChineseInkStyle_v1_0: 96718d4b1924", Version: v1.3.2-RC-258-g394ffa7b
The picture I produced: 
![00169-3311024160](https://github.com/ototadana/sd-face-editor/assets/48752001/e5d87fb6-626f-48c4-a107-09c4f950a65a)
I don't think the algothrim for face recogniation is competent:(

**Comment by ototadana** [comment]
@Gh20221205 

Sorry for the delay. In the latest version (v1.0.0), various face detectors are now available and can be switched depending on the image type. YOLO and Adetailer models are also available. For more information, please check the following

- https://github.com/ototadana/sd-face-editor#workflow-editor
- https://github.com/ototadana/sd-face-editor#example-3-high-accuracy-face-detection-workflow---bingsuadetailer-example

To use this workflow, please apply the following settings in the Face Editor section of the "Settings" tab and restart the Web UI.

- Enable "Search workflows in subdirectories".
- Enable "YOLO" in the "Additional components"

![image](https://github.com/ototadana/sd-face-editor/assets/4137885/5a50c6b7-102d-4cab-a61a-62f3f33495ea)

**Comment by ototadana** [comment]
@Emersonksc 

Thanks for the report.

I also tried the same condition. I suspect the problem is due to incompatibility between Counterfeit and the default face detector rather than lora.

In the latest version we just released (v1.0.0), several face detectors can now be switched depending on the image.

We have experimented with several seeds and recommend that you try "examples/adetailer" as it has the highest detection rate in this case.

For more information and instructions, please see the comments immediately above.

**Comment by ototadana** [comment]
If you disable "Size of the face when recreating" and it still does not work as expected, there may be another cause. Specifically, the faces in the generated images may not be recognized as faces.

Is the style of the image you are creating now realistic or anime style? If it is an anime style, the default face detection feature often does not work well.
