### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by phoenixwarlord** [ototadana/sd-face-editor#97]
TypeError: 'NoneType' object is not subscriptable

It was working fine until now, I'm not sure what happened. I tried updating it to the newest version, but for some reason the newest version is not able to detect the face anymore....

Edit: I realized that the newest version is able to recognize face only when the image is small (512x768), but not able to recognize face after the same image has been scaled up by say 2x size. I tried changing the face detection confidence to the lowest and still not able to get it to detect the face on the enlarged image...

**Comment by ototadana** [comment]
@phoenixwarlord 
Thanks for using this extension.

The default setting is to recreate faces at 512x512, so faces larger than this are ignored. Please try either of the following settings to see if you can get it to recognize larger faces.

- Disable "Ignore faces larger than specified size"
- "Size of the face when recreating" to a number greater than 512.

![image](https://github.com/ototadana/sd-face-editor/assets/4137885/388adda5-394b-4715-857c-a9748c946b06)
