### ISSUE TITLE
Discovered an inexplicable error,[img2img]--[Inpaint sketch]

### ISSUE THREAD

**Issue by blacksky0101** [ototadana/sd-face-editor#98]
when i used it in [img2img]--[Inpaint sketch],
there will be errors and only a small amount of hair will be fixed.
But there are no errors in using it in [img2img]--[img2img]

**Comment by ototadana** [comment]
Thanks for trying this extension.

I have not yet been able to correctly imagine a situation where I would use Face Editor in combination with Inpaint sketch. To avoid misunderstandings, could you tell me about the following?

- What kind of results you are expecting from the combination of the two?
- The actual operations and settings you have performed.

Also, if you see any errors in the terminal, please paste the error message as is.
